__title__ = "AliceBlue_V2"
__description__ = "The Python client for the AliceBlue_V2 trading API"
__url__ = "https://a3.aliceblueonline.com"
__version__ = "1.0.1"
__author__ = "TradeViaPython"
__author_email__ = "TradeViaPython@gmail.com"
__license__ = "Apache License"